%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\Users\leelab\Documents\MATLAB\ongoing\navigation\demographics.xlsx
%    Worksheet: Sheet1
%
% To extend the code to different selected data or a different spreadsheet,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2013/03/11 21:57:31

%% Import the data
clc;clear all;close all;
[~, ~, untitled] = xlsread('R:\ongoing\fmri_oppa\analysis\navigation\demographics_16subj.xlsx','Sheet1','A1:S16');
untitled(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),untitled)) = {''};
factors={'id','gender','age','occupation','major','pool_candidate','mri_taken','visit_sequence','fps_experience','place_emphasis','cognitive_map','standard_scene','verbal','narrative','numbering','imagery','strategy1','strategy2','strategy3','strategy4','associative'};
root_dir=cd;

interview_data=untitled;


interview_mat=nan(size(interview_data,1),10);
interview_mat(:,1)=[1:1:size(interview_data,1)];
for i=1:1:size(interview_data,1)
    %m=0, f=1
    interview_mat(i,2)= strcmp(interview_data{i,2},'f');
    %age
    interview_mat(i,3)=interview_data{i,3};
    %mri_taken=1, no =0
    interview_mat(i,4)= strcmp(interview_data{i,7},'yes');
    %emphasis on place information encoding on the first day high=1, low =0
    interview_mat(i,5)= strcmp(interview_data{i,10},'yes');
    %strategy_verbal: use of verbal component in encoding
    interview_mat(i,6)= strcmp(interview_data{i,13},'yes');
    %strategy_narrative: use of narrative in encoding
    interview_mat(i,7)= strcmp(interview_data{i,14},'yes');
    %strategy_numbering: use of numbering on houses in encoding
    interview_mat(i,8)= strcmp(interview_data{i,15},'yes');
    %strategy_imagery: use of simple imagery in encoding
    interview_mat(i,9)= strcmp(interview_data{i,16},'yes');
    %performance
    if interview_mat(i,4)==1
       load(strcat(interview_data{i,1},'B.mat'));
       interview_mat(i,10)=acc_OCPR;
    else
        interview_mat(i,10)=nan;
    end
    cd(root_dir)
end

save('interviewdata_ver20140620.mat','interview_data','factors','interview_mat');

figure;
scatter(interview_mat(interview_mat(:,6)==1,1),interview_mat(interview_mat(:,6)==1,10),'b');
hold on;
scatter(interview_mat(interview_mat(:,6)==0,1),interview_mat(interview_mat(:,6)==0,10),'r');

figure;
scatter(interview_mat(interview_mat(:,7)==1,1),interview_mat(interview_mat(:,7)==1,10),'b');
hold on;
scatter(interview_mat(interview_mat(:,7)==0,1),interview_mat(interview_mat(:,7)==0,10),'r');
legend('narrative','non-narrative')
xlabel('subject ID');ylabel('performance on OCPR')

[p_val,t_stat,STATS,TERMS]=anovan(interview_mat(interview_mat(:,4)==1,10),interview_mat(interview_mat(:,4)==1,7))

[p_val,t_stat,STATS,TERMS]=anovan(interview_mat(interview_mat(:,4)==1,10),{interview_mat(interview_mat(:,4)==1,7),interview_mat(interview_mat(:,4)==1,5)})



% figure;
% scatter(interview_mat(interview_mat(:,9)==1,1),interview_mat(interview_mat(:,9)==1,10),'b');
% hold on;
% scatter(interview_mat(interview_mat(:,9)==0,1),interview_mat(interview_mat(:,9)==0,10),'r');
% [p_val,t_stat,STATS,TERMS]=anovan(interview_mat(interview_mat(:,4)==1,10),interview_mat(interview_mat(:,4)==1,9))
