
%analyzeudklog.m
close all;clear;clc
warning off
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-Aug-2012 12:13:16


ROOT.Programs = 'X:\E-Phys Analysis\fMRI_oppa\analysis_JM';
ROOT.Raw = 'Y:\EPhysRawData\fmri_oppa';
ROOT.Save = 'X:\E-Phys Analysis\fMRI_oppa\behavior data' ;

 load([ROOT.Save '\func_files.mat'])
FileList = {'CL121121_1','CL121122_1','CL121128_1','CL121227_1','CL130107_1','CL130109_1','CL130114_2','CL130116_2',...
    'CL130121_2','CL130122_1','CL130130_1','CL130219_1','CL130220_1','CL130225_2','CL130226_1','CL130227_1',...
    'JJ231019_1', 'JJ231019_2', 'JJ231019_3', 'JJ231019_4', 'JJ231025_1', 'JJ231025_2', 'JJ231107_1', 'JJ231107_2', 'JJ231107_3', 'JJ231107_4',...
    'JJ231114_1', 'JJ231114_2', 'JJ231114_3', 'JJ231114_4'};
session_perf=table;


for fi=1:30
filename = [FileList{fi}];
filename0=filename(1:10);



addpath(genpath(ROOT.Programs))

if ~exist([ROOT.Save '\' filename0]), mkdir([ROOT.Save '\' filename0]); end

UDK_log_parsing_JM_A_ver1

session_perf.NovDetec(fi) = corr;

% UDK_log_parsing_JM_ver1

% ParsingModule_forJJdata

% MkTrialInfoSheet_forGLM_foJJdata

end

% UDK_log_reorganize_JM