%analyzeudklog.m
close all;clear all;clc
warning off
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 27-Aug-2012 12:13:16

FileList = {'CL121121_1','CL121122_1','CL121128_1','CL121227_1','CL130107_1','CL130109_1','CL130114_2','CL130116_2',...
    'CL130121_2','CL130122_1','CL130130_1','CL130219_1','CL130220_1','CL130225_2','CL130226_1','CL130227_1'};
%
for fi = 1:numel(FileList)
filename = FileList{fi};
filename=[filename 'A'];
Root = ['Y:\EPhysRawData\fmri_oppa\' filename(1:end-1) '\'];
fileToRead1=strcat(filename,'.log');
DELIMITER = ' ';
HEADERLINES = 20727;
no_trials=80;

% Import the file
rawData1 = importdata([Root fileToRead1], DELIMITER, HEADERLINES);

% For some simple files (such as a CSV or JPEG files), IMPORTDATA might
% return a simple array.  If so, generate a structure so that the output
% matches that from the Import Wizard.
[~,name] = fileparts(fileToRead1);
log_data=rawData1;

%%Get timestamps
no_lines=max(size(log_data));
count_pause=0;count_timeframe=0; count_12=0; count_03=0; count_06=0; count_09=0;


%%
line_indice_run_start=1; line_indice_run_end=size(log_data,1);

% line_indice_run_start(1:1:10)=line_indice_pause(5:1:end-1);
% line_indice_run_end(1:1:10)=[line_indice_pause(6:1:end)-3];

line_indice_run=[89 1616 line_indice_run_start; 1613 2907 line_indice_run_end];
%manual adjustments(checked later)
% line_indice_run(2,3)=5166;
% line_indice_run(2,6)=8806;
line_indice_run(2,9)=14356;
% line_indice_run(2,11)=18994;
line_indice_run(2,12)=19272;
% line_indice_run(2,12)=18551;


%%
temp_table=table; t=1;
events_cue=[];
for i=1:size(log_data,1)
    k=strfind(log_data{i},'start_');
    if ~isempty(k)
        string=log_data{i};

        temp_table.trial(t)= str2double(string(end-1:end));
        temp_table.STtime(t)=str2double(string(2:8));
        
        j=i;
        while(isempty(strfind(log_data{j},'choice')))
            string=log_data{j};
            if ~isempty(strfind(log_data{j},'answer'))
                temp_table.EDtime(t)=str2double(string(2:8));
                temp_table.RT(t)=temp_table.EDtime(t)-temp_table.STtime(t);
                temp_table.correct_answer(t)= str2double(string(end));
            end
                       j=j+1;
        end
        temp_table.choice(t)= str2double(log_data{j}(end));
            t=t+1;
    end
end
%%

ODT_table=readtable('D:\Human fMRI project\programs\ORT_table.xlsx');


temp_table.obj_bld=ODT_table.obj_bld;
temp_table.obj_cor=ODT_table.obj_cor;
temp_table.obj_ord=ODT_table.obj_ord;

writetable(temp_table,['D:\Human fMRI project\programs\TrialInfo_' filename '.xlsx']);

writetable(temp_table,[Root 'TrialInfo_' filename '.xlsx']);
end
